/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vrs.gui;
import com.vrs.db.DBConnection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author hp
 */
public class RentalForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalForm.class.getName());

    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
          setLocationRelativeTo(null); // Center the window
    
    // Enable grid lines for table
    jTable1.setShowGrid(true);
    jTable1.setShowHorizontalLines(true);
    jTable1.setShowVerticalLines(true);
    jTable1.setGridColor(Color.LIGHT_GRAY);
    jTable1.setIntercellSpacing(new Dimension(1, 1));
    
    // Add action listeners for Clear and Back buttons
    jButton5.addActionListener(this::jButton5ActionPerformed);
    jButton6.addActionListener(this::jButton6ActionPerformed);
    
    // Set date format hints
    jTextField4.setText(""); // Clear the dd/MM/yyyy text
    jTextField5.setText(""); // Clear the dd/MM/yyyy text
    
    // Load rental data when form opens
    loadRentalData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Rental Form");

        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("ID");

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Cus ID");

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Veh ID");

        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Rental_date");

        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Return_date");

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Total_price");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jTextField2.setBackground(new java.awt.Color(255, 204, 204));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));

        jTextField3.setBackground(new java.awt.Color(255, 204, 204));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));

        jTextField4.setBackground(new java.awt.Color(255, 204, 204));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("dd/MM/yyyy");

        jTextField5.setBackground(new java.awt.Color(255, 204, 204));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("dd/MM/yyyy");

        jTextField6.setBackground(new java.awt.Color(255, 204, 204));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 204, 204));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 3, true));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cus ID", "Veh ID", "Rental_date", "Return_date", "Total_price"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Clear");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(60, 60, 60)
                        .addComponent(jButton4)
                        .addGap(58, 58, 58)
                        .addComponent(jButton5)
                        .addGap(52, 52, 52)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton3)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String custId = jTextField2.getText().trim();
    String vehId = jTextField3.getText().trim();
    String rentalDate = jTextField4.getText().trim();
    String returnDate = jTextField5.getText().trim();
    String totalPrice = jTextField6.getText().trim();

    if(custId.isEmpty() || vehId.isEmpty() || rentalDate.isEmpty() || returnDate.isEmpty() || totalPrice.isEmpty()){
        JOptionPane.showMessageDialog(this, "All fields are required!");
        return;
    }

    try {
        // Validate date format
        if(!rentalDate.matches("\\d{4}-\\d{2}-\\d{2}") || !returnDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Date must be: yyyy-MM-dd (e.g., 2026-02-25)");
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date rDate = sdf.parse(rentalDate);
        Date retDate = sdf.parse(returnDate);
        
        if(retDate.before(rDate)) {
            JOptionPane.showMessageDialog(this, "Return date must be after rental date!");
            return;
        }
        
        Connection con = DBConnection.getConnection();
        
        // ===== CHECK CUSTOMER ID AND SHOW AVAILABLE =====
        PreparedStatement checkCust = con.prepareStatement("SELECT id FROM customer WHERE id=?");
        checkCust.setInt(1, Integer.parseInt(custId));
        ResultSet custRs = checkCust.executeQuery();
        
        if(!custRs.next()) {
            // Get all available customer IDs
            Statement stmt = con.createStatement();
            ResultSet allCust = stmt.executeQuery("SELECT id FROM customer ORDER BY id");
            StringBuilder availableCust = new StringBuilder("✅ Available Customer IDs:\n");
            while(allCust.next()) {
                availableCust.append("ID: ").append(allCust.getInt("id")).append("\n");
            }
            
            JOptionPane.showMessageDialog(this, 
                "❌ Customer ID " + custId + " not found!\n\n" + 
                availableCust.toString() +
                "\nPlease use one of these IDs.", 
                "Invalid Customer ID", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // ===== CHECK VEHICLE ID AND SHOW AVAILABLE =====
        PreparedStatement checkVeh = con.prepareStatement("SELECT id FROM vehicle WHERE id=?");
        checkVeh.setInt(1, Integer.parseInt(vehId));
        ResultSet vehRs = checkVeh.executeQuery();
        
        if(!vehRs.next()) {
            // Get all available vehicle IDs
            Statement stmt = con.createStatement();
            ResultSet allVeh = stmt.executeQuery("SELECT id FROM vehicle ORDER BY id");
            StringBuilder availableVeh = new StringBuilder("✅ Available Vehicle IDs:\n");
            while(allVeh.next()) {
                availableVeh.append("ID: ").append(allVeh.getInt("id")).append("\n");
            }
            
            JOptionPane.showMessageDialog(this, 
                "❌ Vehicle ID " + vehId + " not found!\n\n" + 
                availableVeh.toString() +
                "\nPlease use one of these IDs.", 
                "Invalid Vehicle ID", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Insert rental
        String sql = "INSERT INTO rentals (customer_id, vehicle_id, rental_date, return_date, total_price) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(custId));
        pst.setInt(2, Integer.parseInt(vehId));
        pst.setDate(3, new java.sql.Date(rDate.getTime()));
        pst.setDate(4, new java.sql.Date(retDate.getTime()));
        pst.setDouble(5, Double.parseDouble(totalPrice));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, 
            "✅ Rental Added Successfully!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
        
        clearFields();
        loadRentalData();

        pst.close();
        con.close();

    } catch(java.text.ParseException e) {
        JOptionPane.showMessageDialog(this, 
            "❌ Invalid date! Use yyyy-MM-dd (e.g., 2026-02-25)", 
            "Date Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "❌ IDs and Price must be numbers!", 
            "Number Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, 
            "❌ Error: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // First try to get ID from text field
    String idText = jTextField1.getText().trim();
    
    if(!idText.isEmpty()) {
        // If ID is typed, use that
        try {
            int id = Integer.parseInt(idText);
            deleteRentalById(id);
            return;
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ID format!");
            return;
        }
    }
    
    // If no ID typed, try selected row
    int selectedRow = jTable1.getSelectedRow();
    
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please type an ID or select a row to delete");
        return;
    }
    
    try {
        // Get ID from selected row
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Delete Rental ID " + id + "?", 
            "Confirm Delete", 
            JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION) {
            deleteRentalById(id);
        }

    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

// Helper method to delete by ID
private void deleteRentalById(int id) {
    try {
        Connection con = DBConnection.getConnection();
        String sql = "DELETE FROM rentals WHERE id=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, id);
        
        int rowsAffected = pst.executeUpdate();
        
        if(rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Rental ID " + id + " Deleted Successfully!");
            clearFields();
            loadRentalData();
        } else {
            JOptionPane.showMessageDialog(this, "Rental ID " + id + " not found!");
        }
        
        pst.close();
        con.close();

    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String id = jTextField1.getText().trim();
    String custId = jTextField2.getText().trim();
    String vehId = jTextField3.getText().trim();
    String rentalDate = jTextField4.getText().trim();
    String returnDate = jTextField5.getText().trim();
    String totalPrice = jTextField6.getText().trim();

    if(id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Rental ID to update");
        return;
    }

    if(custId.isEmpty() || vehId.isEmpty() || rentalDate.isEmpty() || returnDate.isEmpty() || totalPrice.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        Date rDate = sdf.parse(rentalDate);
        Date retDate = sdf.parse(returnDate);
        
        Connection con = DBConnection.getConnection();
        
        // Check if customer exists
        PreparedStatement checkCust = con.prepareStatement("SELECT id FROM customer WHERE id=?");
        checkCust.setInt(1, Integer.parseInt(custId));
        ResultSet custRs = checkCust.executeQuery();
        
        // Check if vehicle exists
        PreparedStatement checkVeh = con.prepareStatement("SELECT id FROM vehicle WHERE id=?");
        checkVeh.setInt(1, Integer.parseInt(vehId));
        ResultSet vehRs = checkVeh.executeQuery();
        
        if(!custRs.next()) {
            JOptionPane.showMessageDialog(this, "Customer ID not found!");
            return;
        }
        
        if(!vehRs.next()) {
            JOptionPane.showMessageDialog(this, "Vehicle ID not found!");
            return;
        }
        
        String sql = "UPDATE rentals SET customer_id=?, vehicle_id=?, rental_date=?, return_date=?, total_price=? WHERE id=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(custId));
        pst.setInt(2, Integer.parseInt(vehId));
        pst.setDate(3, new java.sql.Date(rDate.getTime()));
        pst.setDate(4, new java.sql.Date(retDate.getTime()));
        pst.setDouble(5, Double.parseDouble(totalPrice));
        pst.setInt(6, Integer.parseInt(id));

        int rowsAffected = pst.executeUpdate();

        if(rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Rental Updated Successfully!");
            clearFields();
            loadRentalData();
        } else {
            JOptionPane.showMessageDialog(this, "Rental ID not found!");
        }

        pst.close();
        con.close();

    } catch(java.text.ParseException e) {
        JOptionPane.showMessageDialog(this, "Invalid date format! Use yyyy-MM-dd");
    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "IDs and Price must be numbers!");
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Try to get ID from text field first
    String idText = jTextField1.getText().trim();
    
    if(!idText.isEmpty()) {
        // If ID is typed, use that
        try {
            int id = Integer.parseInt(idText);
            viewRentalById(id);
            return;
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ID format!");
            return;
        }
    }
    
    // If no ID typed, try selected row
    int selectedRow = jTable1.getSelectedRow();
    
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please type an ID or select a row to view");
        return;
    }
    
    try {
        // Get data from selected row
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        int custId = (int) jTable1.getValueAt(selectedRow, 1);
        int vehId = (int) jTable1.getValueAt(selectedRow, 2);
        String rentalDate = (String) jTable1.getValueAt(selectedRow, 3);
        String returnDate = (String) jTable1.getValueAt(selectedRow, 4);
        double totalPrice = (double) jTable1.getValueAt(selectedRow, 5);
        
        // Fill fields
        jTextField1.setText(String.valueOf(id));
        jTextField2.setText(String.valueOf(custId));
        jTextField3.setText(String.valueOf(vehId));
        jTextField4.setText(rentalDate);
        jTextField5.setText(returnDate);
        jTextField6.setText(String.valueOf(totalPrice));
        
        JOptionPane.showMessageDialog(this, "Rental ID " + id + " loaded!");

    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

// Helper method to view by ID
private void viewRentalById(int id) {
    try {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT * FROM rentals WHERE id=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, id);
        
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            jTextField1.setText(String.valueOf(rs.getInt("id")));
            jTextField2.setText(String.valueOf(rs.getInt("customer_id")));
            jTextField3.setText(String.valueOf(rs.getInt("vehicle_id")));
            jTextField4.setText(sdf.format(rs.getDate("rental_date")));
            jTextField5.setText(sdf.format(rs.getDate("return_date")));
            jTextField6.setText(rs.getString("total_price"));
            
            JOptionPane.showMessageDialog(this, "Rental ID " + id + " found!");
        } else {
            JOptionPane.showMessageDialog(this, "Rental ID " + id + " not found!");
        }
        
        rs.close();
        pst.close();
        con.close();
        
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    clearFields();
    JOptionPane.showMessageDialog(this, 
        "All fields cleared!", 
        "Cleared", 
        JOptionPane.INFORMATION_MESSAGE);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Dashboard dashboard = new Dashboard();
    dashboard.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

 private void loadRentalData() {
    try {
        Connection con = DBConnection.getConnection();
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM rentals ORDER BY id");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        while(rs.next()) {
            Object[] row = {
                rs.getInt("id"),  // ← Ye already original ID hai
                rs.getInt("customer_id"),
                rs.getInt("vehicle_id"),
                sdf.format(rs.getDate("rental_date")),
                sdf.format(rs.getDate("return_date")),
                rs.getDouble("total_price")
            };
            model.addRow(row);
        }
        
        rs.close();
        stmt.close();
        con.close();
        
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        e.printStackTrace();
    }
}

private void clearFields() {
    jTextField1.setText(""); // ID
    jTextField2.setText(""); // Customer ID
    jTextField3.setText(""); // Vehicle ID
    jTextField4.setText(""); // Rental Date
    jTextField5.setText(""); // Return Date
    jTextField6.setText(""); // Total Price
}
}
