/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vrs.gui;
import com.vrs.db.DBConnection;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class VehicleForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VehicleForm.class.getName());

    /**
     * Creates new form VehicleForm
     */
    public VehicleForm() {
        initComponents();
           setLocationRelativeTo(null);
    
    // Enable grid lines
    jTable3.setShowGrid(true);
    jTable3.setShowHorizontalLines(true);
    jTable3.setShowVerticalLines(true);
    jTable3.setGridColor(Color.LIGHT_GRAY);
    
    // ADD THESE ACTION LISTENERS:
    jButton5.addActionListener(this::jButton5ActionPerformed);
    jButton6.addActionListener(this::jButton6ActionPerformed);
    
    // Load data
    loadVehicleData();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Vehicle Form");

        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Name");

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Type");

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("price_per_day");

        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Veh ID");

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jTextField2.setBackground(new java.awt.Color(255, 204, 204));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));

        jTextField3.setBackground(new java.awt.Color(255, 204, 204));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));

        jTextField4.setBackground(new java.awt.Color(255, 204, 204));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Clear");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jTable3.setBackground(new java.awt.Color(255, 204, 204));
        jTable3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 3, true));
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Veh ID", "Name", "Type", "Title 4"
            }
        ));
        jTable3.setSelectionForeground(new java.awt.Color(255, 102, 102));
        jTable3.setShowGrid(true);
        jTable3.setShowHorizontalLines(true);
        jTable3.setShowVerticalLines(true);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton2)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(65, 65, 65)
                                .addComponent(jButton4)
                                .addGap(65, 65, 65)
                                .addComponent(jButton5)
                                .addGap(55, 55, 55)
                                .addComponent(jButton6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String name = jTextField1.getText().trim();
    String type = jTextField2.getText().trim();
    String price = jTextField3.getText().trim();

    if(name.isEmpty() || type.isEmpty() || price.isEmpty()){
        JOptionPane.showMessageDialog(this, "All fields are required!");
        return;
    }

    try {
        Connection con = DBConnection.getConnection();
        String sql = "INSERT INTO vehicle (name, type, price_per_day) VALUES (?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, name);
        pst.setString(2, type);
        pst.setDouble(3, Double.parseDouble(price));
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Vehicle Added Successfully!");
        clearFields();
        loadVehicleData();
        pst.close();
        con.close();

    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Price must be a number!");
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      String id = jTextField4.getText().trim();

    if(id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Vehicle ID to delete");
        return;
    }

    try {
        Connection con = DBConnection.getConnection();
        
        // Check if vehicle has rentals
        String checkSql = "SELECT COUNT(*) FROM rentals WHERE vehicle_id = ?";
        PreparedStatement checkPst = con.prepareStatement(checkSql);
        checkPst.setInt(1, Integer.parseInt(id));
        ResultSet rs = checkPst.executeQuery();
        rs.next();
        int rentalCount = rs.getInt(1);
        
        if(rentalCount > 0) {
            int confirm = JOptionPane.showConfirmDialog(this, 
                "This vehicle has " + rentalCount + " rental record(s). Delete anyway?", 
                "Warning", JOptionPane.YES_NO_OPTION);
            
            if(confirm == JOptionPane.YES_OPTION) {
                PreparedStatement deleteRentalsPst = con.prepareStatement("DELETE FROM rentals WHERE vehicle_id = ?");
                deleteRentalsPst.setInt(1, Integer.parseInt(id));
                deleteRentalsPst.executeUpdate();
                
                PreparedStatement deleteVehiclePst = con.prepareStatement("DELETE FROM vehicle WHERE id = ?");
                deleteVehiclePst.setInt(1, Integer.parseInt(id));
                deleteVehiclePst.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Vehicle and rental history deleted!");
                clearFields();
                loadVehicleData();
            }
        } else {
            PreparedStatement deletePst = con.prepareStatement("DELETE FROM vehicle WHERE id=?");
            deletePst.setInt(1, Integer.parseInt(id));
            
            if(deletePst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Vehicle Deleted Successfully!");
                clearFields();
                loadVehicleData();
            } else {
                JOptionPane.showMessageDialog(this, "Vehicle ID not found!");
            }
        }
        con.close();

    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

     // TODO add your handling code here:
     String id = jTextField4.getText().trim();
    String name = jTextField1.getText().trim();
    String type = jTextField2.getText().trim();
    String price = jTextField3.getText().trim();

    if(id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Vehicle ID to update");
        return;
    }
    
    if(name.isEmpty() || type.isEmpty() || price.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    try {
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("UPDATE vehicle SET name=?, type=?, price_per_day=? WHERE id=?");
        pst.setString(1, name);
        pst.setString(2, type);
        pst.setDouble(3, Double.parseDouble(price));
        pst.setInt(4, Integer.parseInt(id));

        if(pst.executeUpdate() > 0) {
            JOptionPane.showMessageDialog(this, "Vehicle Updated Successfully!");
            clearFields();
            loadVehicleData();
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle ID not found!");
        }
        pst.close();
        con.close();

    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Price must be a number!");
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  String id = jTextField4.getText().trim();

    if(id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Vehicle ID to view");
        return;
    }

    try {
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("SELECT * FROM vehicle WHERE id=?");
        pst.setInt(1, Integer.parseInt(id));
        ResultSet rs = pst.executeQuery();

        if(rs.next()){
            jTextField1.setText(rs.getString("name"));
            jTextField2.setText(rs.getString("type"));
            jTextField3.setText(rs.getString("price_per_day"));
            JOptionPane.showMessageDialog(this, "Vehicle found!");
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle Not Found with ID: " + id);
            clearFields();
        }
        rs.close();
        pst.close();
        con.close();

    } catch(NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID must be a number!");
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 clearFields();
    JOptionPane.showMessageDialog(this, "All fields cleared!", "Cleared", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 Dashboard dashboard = new Dashboard();
    dashboard.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VehicleForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void loadVehicleData() {
    try {
        Connection con = DBConnection.getConnection();
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM vehicle ORDER BY id");
        
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        
        while(rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),  // ← ORIGINAL DATABASE ID
                rs.getString("name"),
                rs.getString("type"),
                rs.getString("price_per_day")
            });
        }
        rs.close();
        stmt.close();
        con.close();
        
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
    }
}
private void clearFields() {
    jTextField4.setText(""); // ID
    jTextField1.setText(""); // Name
    jTextField2.setText(""); // Type
    jTextField3.setText(""); // Price
}
   
}
